name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
        use-uv:
          - true
          - false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - uses: ./
        with:
          use-uv: ${{ matrix.use-uv }}

      - run: rye --version
