name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
        use-uv:
          - true
          - false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: ./
        with:
          use-uv: ${{ matrix.use-uv }}

      - run: rye --version
