name: validate renovate

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'renovate.json5'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator
